language: node_js

node_js:
  - "8"

before_install:
  - sudo apt-get install -y a2ps

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
