language: node_js

node_js:
  - "8"

script: yarn build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
